-- Seed the words table with sample words for the game
INSERT INTO words (word) VALUES
  ('Pizza'),
  ('Ocean'),
  ('Guitar'),
  ('Mountain'),
  ('Coffee'),
  ('Sunset'),
  ('Dragon'),
  ('Library'),
  ('Bicycle'),
  ('Rainbow'),
  ('Volcano'),
  ('Penguin'),
  ('Telescope'),
  ('Waterfall'),
  ('Chocolate'),
  ('Lighthouse'),
  ('Butterfly'),
  ('Thunder'),
  ('Carnival'),
  ('Astronaut'),
  ('Treasure'),
  ('Fireworks'),
  ('Dinosaur'),
  ('Castle'),
  ('Submarine'),
  ('Tornado'),
  ('Pyramid'),
  ('Unicorn'),
  ('Glacier'),
  ('Phoenix')
ON CONFLICT (word) DO NOTHING;
