-- Clear existing words and add new categorized words
DELETE FROM words;

-- 🍔 Food & Drinks (15)
INSERT INTO words (word) VALUES
  ('Pizza'),
  ('Burger'),
  ('Sandwich'),
  ('Ice Cream'),
  ('Coffee'),
  ('Tea'),
  ('Cake'),
  ('Spaghetti'),
  ('Sushi'),
  ('Chocolate'),
  ('Fried Rice'),
  ('Soup'),
  ('French Fries'),
  ('Salad'),
  ('Popcorn'),

-- 🌍 Places (15)
  ('Beach'),
  ('Airport'),
  ('Hospital'),
  ('Classroom'),
  ('Library'),
  ('Mountain'),
  ('Zoo'),
  ('Restaurant'),
  ('Cinema'),
  ('Market'),
  ('Park'),
  ('Hotel'),
  ('Office'),
  ('Stadium'),
  ('Museum'),

-- 🐾 Animals (15)
  ('Dog'),
  ('Cat'),
  ('Elephant'),
  ('Lion'),
  ('Tiger'),
  ('Monkey'),
  ('Dolphin'),
  ('Fish'),
  ('Snake'),
  ('Frog'),
  ('Bird'),
  ('Horse'),
  ('Panda'),
  ('Eagle'),
  ('Penguin'),

-- ⚙️ Objects & Everyday Items (20)
  ('Phone'),
  ('Laptop'),
  ('Watch'),
  ('Table'),
  ('Chair'),
  ('Pen'),
  ('Book'),
  ('Bag'),
  ('Bottle'),
  ('Mirror'),
  ('Scissors'),
  ('Keyboard'),
  ('Remote'),
  ('Light Bulb'),
  ('Wallet'),
  ('Umbrella'),
  ('Sunglasses'),
  ('Toothbrush'),
  ('Camera'),
  ('Pillow'),

-- 👕 Clothing & Accessories (10)
  ('Shoes'),
  ('Hat'),
  ('T-shirt'),
  ('Jacket'),
  ('Scarf'),
  ('Socks'),
  ('Gloves'),
  ('Glasses'),
  ('Belt'),
  ('Dress'),

-- 💻 Technology & Gadgets (10)
  ('Headphones'),
  ('Drone'),
  ('Charger'),
  ('Mouse'),
  ('Robot'),
  ('Microphone'),
  ('Smartwatch'),
  ('Tablet'),
  ('Speaker'),
  ('TV'),

-- 🧠 Activities & Concepts (10)
  ('Dancing'),
  ('Singing'),
  ('Cooking'),
  ('Driving'),
  ('Reading'),
  ('Swimming'),
  ('Sleeping'),
  ('Studying'),
  ('Shopping'),
  ('Drawing'),

-- 🔥 Special "Confusable" or Funny Ones (5)
  ('Pool'),
  ('Plane'),
  ('Pizza Cutter'),
  ('Banana'),
  ('Password')
ON CONFLICT (word) DO NOTHING;
