-- Clear existing words and add new categorized words
DELETE FROM words;

-- 🍕 Food & Drinks (25)
INSERT INTO words (word) VALUES
  ('Pasta'),
  ('Steak'),
  ('Noodles'),
  ('Curry'),
  ('Smoothie'),
  ('Donut'),
  ('Taco'),
  ('Juice'),
  ('Coffee Latte'),
  ('Biryani'),
  ('Muffin'),
  ('Hotdog'),
  ('Pancake'),
  ('Milkshake'),
  ('Cheeseburger'),
  ('Lasagna'),
  ('Samosa'),
  ('Spring Roll'),
  ('Falooda'),
  ('Omelette'),
  ('Brownie'),
  ('Sushi Roll'),
  ('Grilled Chicken'),
  ('Ice Latte'),
  ('French Toast'),

-- 🌍 Places (25)
  ('Desert'),
  ('Forest'),
  ('Temple'),
  ('Bridge'),
  ('River'),
  ('Island'),
  ('Cave'),
  ('Village'),
  ('Bus Station'),
  ('Train'),
  ('Amusement Park'),
  ('Skyscraper'),
  ('Harbor'),
  ('Castle'),
  ('Airport'),
  ('Beach'),
  ('Market'),
  ('Stadium'),
  ('Restaurant'),
  ('Mall'),
  ('Playground'),
  ('Subway'),
  ('School'),
  ('Tower'),

-- 🐾 Animals (25)
  ('Bear'),
  ('Fox'),
  ('Rabbit'),
  ('Wolf'),
  ('Deer'),
  ('Shark'),
  ('Octopus'),
  ('Kangaroo'),
  ('Crocodile'),
  ('Giraffe'),
  ('Parrot'),
  ('Bat'),
  ('Seal'),
  ('Camel'),
  ('Turtle'),
  ('Whale'),
  ('Dolphin'),
  ('Leopard'),
  ('Zebra'),
  ('Swan'),
  ('Eagle'),
  ('Pigeon'),
  ('Chameleon'),
  ('Crab'),
  ('Penguin'),

-- ⚙️ Objects & Everyday Items (25)
  ('Clock'),
  ('Razor'),
  ('Calculator'),
  ('Toaster'),
  ('Mug'),
  ('Spoon'),
  ('Notebook'),
  ('Key'),
  ('Helmet'),
  ('Door'),
  ('Fan'),
  ('Ruler'),
  ('Bed'),
  ('Towel'),
  ('Radio'),
  ('Cable'),
  ('Basket'),
  ('Hammer'),
  ('Plug'),
  ('Calendar'),
  ('Lock'),
  ('Plate'),
  ('Globe'),
  ('Trash Can'),
  ('Iron'),

-- 👕 Clothing & Accessories (25)
  ('Sweater'),
  ('Jeans'),
  ('Blazer'),
  ('Cap'),
  ('Skirt'),
  ('Coat'),
  ('Tie'),
  ('Boots'),
  ('Hoodie'),
  ('Bracelet'),
  ('Ring'),
  ('Watch'),
  ('Earrings'),
  ('Necklace'),
  ('Gloves'),
  ('Sandals'),
  ('Shorts'),
  ('Backpack'),
  ('Sunglasses'),
  ('Scarf'),
  ('Belt'),
  ('Jersey'),
  ('Suit'),
  ('Mask'),
  ('Uniform'),

-- 💻 Technology & Gadgets (25)
  ('Game Console'),
  ('VR Headset'),
  ('Projector'),
  ('Webcam'),
  ('Hard Drive'),
  ('Power Bank'),
  ('Tablet'),
  ('Graphics Card'),
  ('Smart TV'),
  ('Bluetooth'),
  ('Processor'),
  ('Router'),
  ('Smartphone'),
  ('Drone'),
  ('Microphone'),
  ('Tripod'),
  ('Flash Drive'),
  ('Memory Card'),
  ('Monitor'),
  ('Smartwatch'),
  ('Speaker'),
  ('Laptop Stand'),
  ('Cooling Pad'),
  ('Printer'),

-- 🧠 Activities & Concepts (25)
  ('Jogging'),
  ('Meditation'),
  ('Traveling'),
  ('Painting'),
  ('Writing'),
  ('Gaming'),
  ('Cycling'),
  ('Fishing'),
  ('Cleaning'),
  ('Photography'),
  ('Reading'),
  ('Running'),
  ('Cooking'),
  ('Sleeping'),
  ('Shopping'),
  ('Dancing'),
  ('Singing'),
  ('Studying'),
  ('Surfing'),
  ('Climbing'),
  ('Boxing'),
  ('Gardening'),
  ('Drawing'),
  ('Skating'),
  ('Driving'),

-- 🌎 Countries (25)
  ('Bangladesh'),
  ('India'),
  ('Nepal'),
  ('Japan'),
  ('China'),
  ('Brazil'),
  ('France'),
  ('Germany'),
  ('Italy'),
  ('Spain'),
  ('Egypt'),
  ('Australia'),
  ('Canada'),
  ('Mexico'),
  ('United States'),
  ('United Kingdom'),
  ('Russia'),
  ('Turkey'),
  ('Saudi Arabia'),
  ('Indonesia'),
  ('Thailand'),
  ('South Korea'),
  ('Pakistan'),
  ('Argentina'),
  ('South Africa'),

-- 🔥 Special "Confusable" or Funny Ones (25)
  ('Toilet Paper'),
  ('Hot Potato'),
  ('Invisible Ink'),
  ('USB Stick'),
  ('Broken Charger'),
  ('Fake ID'),
  ('Forgotten Key'),
  ('Wrong Number'),
  ('Cracked Screen'),
  ('Empty Wallet'),
  ('Lost Remote'),
  ('Expired Coupon'),
  ('No Signal'),
  ('Missing Shoe'),
  ('Spicy Ice Cream'),
  ('Loud Neighbor'),
  ('Unsent Message'),
  ('Lagging WiFi'),
  ('Fried Charger'),
  ('Auto Reply'),
  ('Ghost Notification'),
  ('Stuck Zipper'),
  ('Fake Friend'),
  ('Dead Battery'),

-- 🚗 Vehicles (25)
  ('Car'),
  ('Bus'),
  ('Truck'),
  ('Motorcycle'),
  ('Bicycle'),
  ('Train'),
  ('Airplane'),
  ('Helicopter'),
  ('Boat'),
  ('Ship'),
  ('Scooter'),
  ('Submarine'),
  ('Ambulance'),
  ('Fire Truck'),
  ('Taxi'),
  ('Van'),
  ('Tractor'),
  ('Rickshaw'),
  ('Jeep'),
  ('Pickup'),
  ('Skateboard'),
  ('Electric Car'),
  ('Cargo Plane'),
  ('Cruise'),
  ('Bullet Train'),

-- 👷 Professions (25)
  ('Doctor'),
  ('Engineer'),
  ('Teacher'),
  ('Pilot'),
  ('Chef'),
  ('Artist'),
  ('Photographer'),
  ('Actor'),
  ('Singer'),
  ('Police Officer'),
  ('Firefighter'),
  ('Nurse'),
  ('Lawyer'),
  ('Architect'),
  ('Mechanic'),
  ('Farmer'),
  ('Journalist'),
  ('Scientist'),
  ('Designer'),
  ('Plumber'),
  ('Driver'),
  ('Soldier'),
  ('Electrician'),
  ('Programmer'),
  ('Barber')
  ('Surgeon');
  ('Journalist');
ON CONFLICT (word) DO NOTHING;
